### ISSUE TITLE
map visibility

### ISSUE THREAD

**Issue by ksobon** [ladybug-tools/epwmap#15]
@mostaphaRoudsari can we enable "no labels" for the topographical map/BW view?

**Comment by mostaphaRoudsari** [comment]
Hi @ksobon! I'm not sure if I totally get what you are asking for. Do you want the google map to have no details? Can you provide an example?

**Comment by mostaphaRoudsari** [comment]
Now you can do this!
![screenshot 15](https://cloud.githubusercontent.com/assets/2915573/25494622/3b933a36-2b48-11e7-98f5-f6b78ae34581.png)
