### ISSUE TITLE
Missing Hours of Heat / Cold Stress for TMY3 data

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/epwmap#19]
I just noticed that this information appears to be missing:
![missing hours of heatcool stress](https://cloud.githubusercontent.com/assets/5567574/25464525/d2f7d838-2aca-11e7-9656-f60499004190.jpg)

**Comment by mostaphaRoudsari** [comment]
Locations from onebuilding didn't have comfort data. This is fixed now via https://github.com/ladybug-tools/epwmap/commit/0dfa70fc6dcf7f6ff18dde01b64082cd11dd8a9b
