### ISSUE TITLE
Basis for Comfort Hours

### ISSUE THREAD

**Issue by devngc** [ladybug-tools/epwmap#21]
@mostaphaRoudsari,
I'm interested in knowing the basis behind the Hours of Comfort result on EPWmap. Can you please point me to the calc in your code or any other resource?

**Comment by mostaphaRoudsari** [comment]
Hi @devngc, it's all per-calculated using ladybug. You can find the values in [this csv file](https://github.com/ladybug-tools/epwmap/blob/gh-pages/data/epw_weather_data.csv).

**Comment by devngc** [comment]
@mostaphaRoudsari,
I see that the column with header "no_thermal_stress" is being read for "Hours of comfort." Can you please point to the code in ladybug that calculates these numbers?  I am merely interested in the underlying calculation method. Some other resource will work as well. 
Thank you!

**Comment by mostaphaRoudsari** [comment]
Check out this link: https://github.com/mostaphaRoudsari/ladybug/blob/master/src/Ladybug_Outdoor%20Comfort%20Calculator.py and http://www.utci.org/

**Comment by devngc** [comment]
Alright. So it is UTCI. Thank you!
