### ISSUE TITLE
Can not open EPWmap in multiple browsers

### ISSUE THREAD

**Issue by zhangzhennico** [ladybug-tools/epwmap#24]
Hello, I can not open the website when I try to copy the epw file position for my simulation. I tryied several browsers and always got the same freezed page. I really need the URL postion of Xingyi,Guizhou,China for my simulations and I ask for all of your help. I konw it is a very simple question but I can not go on with my simulation without it.  Many thanks,.
Anyone who can help me to solve this problem or help me to copy the URL postion of  the weather data?

Thanks a lot.

**Comment by mostaphaRoudsari** [comment]
@zhangzhennico, this is the path: https://www.energyplus.net/weather-download/asia_wmo_region_2/CHN//CHN_Guizhou.Xingyi.579020_CSWD/all

Is this a new issue? Can you share a screenshot?
cc: @MingboPeng

**Comment by zhangzhennico** [comment]
![capture](https://user-images.githubusercontent.com/26587689/40033467-2962873e-582b-11e8-9070-50d1c6688622.PNG)
This is the screennap and I try it for many time and multiple browsers, like firefox, chrome. Because I think it may be was caused by internet problems. I ask my frined who lives in Singapore to help and she got the same issue.
Thanks a lot for your help and I am not sure it is a new problem or not. I also need the weather file UPL where you can copy on the map and hope it would not trouble you so much. Thanks a lot.

**Comment by mostaphaRoudsari** [comment]
@zhangzhennico, try now. We don't use GoogleMaps anymore which should address your issue with loading the page.
