### ISSUE TITLE
Optimize speed when zooming and panning.

### ISSUE THREAD

**Issue by Vyrwn** [ladybug-tools/epwmap#27]
@mostaphaRoudsari , I was having a random thought the other day about the website and desided to have a go but not succefully yet, but I want first to see what you think.
As much as I love the epwmap it is quite heavy when you want to navigate around without typing in the search bar.
I was trying to implement a function where it filters out all data when draging / zooming and then filters them in again after 1s.

The idea is that while you zoom or pan, you dont have any of the heavy data showing and once you arive to the area you like then it brings back all the information.

I was trying something like the image below without success, but if you agree on this I will figure it out.

![image](https://user-images.githubusercontent.com/10517740/47869312-8d7cd400-ddfe-11e8-8fbf-0a5cd5762032.png)

**Comment by saeranv** [comment]
Hope you guys can fix this, it's true the epwmap is too heavy to use without the search bar.

**Comment by mostaphaRoudsari** [comment]
@Vyrwn anything the improve the performance is welcome!

Also keep in mind that since Google Maps is now paid we might move to other available options. @MingboPeng has already done some exploration in this area to make epwmap accessible to Chinese users!

**Comment by mostaphaRoudsari** [comment]
@Vyrwn, I switched epwmap to use mapbox and their API. On my machine the page is now working smoothly. I think we can close this issue.

**Comment by mostaphaRoudsari** [comment]
Now I added all the new locations and it is still working fine! So I'm going to close this issue. Feel free to reopen if you still think there is a problem with zoom and pan.

**Comment by saeranv** [comment]
Huge improvement, thanks!

**Comment by Vyrwn** [comment]
@mostaphaRoudsari this is very nice now. Thanks again!!
