### ISSUE TITLE
OpenBuilding database - how often is updated?

### ISSUE THREAD

**Issue by ayezioro** [ladybug-tools/epwmap#28]

**Comment by ayezioro** [comment]
Hi @mostaphaRoudsari,
Just wonder how often the database for OneBuilding weather data location is done?
Lately some locations were added that i can't find using the epwmap. Like today's middle east's.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Hi @ayezioro, and this will be my New Year present for you! I added all the new weather files. Check now: http://www.ladybug.tools/epwmap/

**Comment by ayezioro** [comment]
This is great @mostaphaRoudsari !!
Thanks and a happy new year to you.

-A.
