### ISSUE TITLE
Error in one of the links in epwmap

### ISSUE THREAD

**Issue by the-donn** [ladybug-tools/epwmap#30]
I have found that the Queenstown New Zealand location on EPWMAP does not work (404 error, suggesting the resource is not there, but I think it is actually the resource no longer has the name allocated in the epwmap link).

In fact, on onebuilding.org there are three files for this one town:  
They are:
http://climate.onebuilding.org/WMO_Region_5_Southwest_Pacific/NZL_New_Zealand/OTA_Otago/NZL_OTA_Queenstown.AP.938310_TMYx.zip

http://climate.onebuilding.org/WMO_Region_5_Southwest_Pacific/NZL_New_Zealand/OTA_Otago/NZL_OTA_Queenstown.AP.938310_TMYx.2004-2018.zip 

http://climate.onebuilding.org/WMO_Region_5_Southwest_Pacific/NZL_New_Zealand/OTA_Otago/NZL_OTA_Queenstown.QL.938310_NIWA.zip

The epwmap links to this address:
http://climate.onebuilding.org/WMO_Region_5_Southwest_Pacific/NZL_New_Zealand/OTA_Otago/NZL_OTA_Queenstown.AP.938310_TMYx.2003-2017.zip 

Is there a way of flagging these for correction when people find them?

**Comment by gouldingken** [comment]
I came here to report a similar issue for links in Africa. Seems to be the same exact pattern.

http://climate.onebuilding.org/WMO_Region_1_Africa/MDG_Madagascar/AV_Antananarivo/MDG_AV_Antsirabe.AP.671070_TMYx.2003-2017.zip

should be:

http://climate.onebuilding.org/WMO_Region_1_Africa/MDG_Madagascar/AV_Antananarivo/MDG_AV_Antsirabe.AP.671070_TMYx.2004-2018.zip

**Comment by mostaphaRoudsari** [comment]
Thank you @gouldingken! It's just that when they update the links on climate onebuilding they change the filenames! I should probably talk to Dru and Linda and see if they can change this and use the same file name and save the metadata somewhere else.

**Comment by mostaphaRoudsari** [comment]
The links should be fixed now. Feel free to reopen otherwise.
