### ISSUE TITLE
define your variables on the map legend

### ISSUE THREAD

**Issue by dhardestylewis** [ladybug-tools/epwmap#36]
https://www.ladybug.tools/epwmap/

**Comment by mostaphaRoudsari** [comment]
Hi @dhardestylewis, is this a question about the map legends?

In that case, those are the weather data sources. See here: https://energyplus.net/weather/sources

For TMYx see here: https://climate.onebuilding.org/

**Comment by dhardestylewis** [comment]
Figured them for sources, but y'all could make it clear up front
